# Generated by Django 5.2.16 on 2026-09-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='DMX Digital Solutions', max_length=150)),
                ('motto', models.CharField(default='Building Intelligent Digital Solutions', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Short description of DMX Digital Solutions.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/branding/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True, verbose_name='X URL')),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
